inherit_from: configs/LiFT_dataset/lift_dataset.yaml
data:
  scene_name: jug_translation_z_prod
  input_path: datasets/LiFT_dataset/jug_translation_z_prod/
  output_path: output/LiFT_dataset/jug_translation_z_prod/
cam:  # intrinsics don't matter, read from a file
  H: 720
  W: 1280
  fx: 913.108126
  fy: 913.572156
  cx: 621.637014 
  cy: 376.93883
  crop_edge: 0
  distortion: [0, 0, 0, 0, 0]