inherit_from: configs/ycbv_lf/ycbv_lf.yaml
data:
  scene_name: bleach_hard_00_03_chaitanya
  input_path: datasets/ycbv_lf/bleach_hard_00_03_chaitanya/
  output_path: output/ycbv_lf/bleach_hard_00_03_chaitanya/
cam:  # intrinsics don't matter, read from a file
  H: 480
  W: 640
  fx: 319.5820007324219
  fy: 417.1186828613281
  cx: 320.21498476769557
  cy: 244.34866808710467
  crop_edge: 0
  distortion: [0, 0, 0, 0, 0]